### ISSUE TITLE
Doesn't work with workspaces

### ISSUE THREAD

**Issue by sergei-dyshel** [alternate-file/vscode-alternate-file#2]
By looking at the code: `vscode.workspace.findFiles('.projections.json')` won't find anything in workspace project (with one or more workspace folders). One has either use `**/.projections.json` or (the correct way) initialize projections per workspace folder, which is more work though.

**Comment by will-wow** [comment]
Hey @sergei-dyshel, thanks for the report!

I finally got some time to work on this again, and re-worked it in PR 
https://github.com/alternate-file/vscode-alternate-file/pull/3. Now every time you run one of the commands it'll walk the file tree to find the closest `.projections.json` file, and use that. At least for me, that's got this extension working fine in a multi-root workspace.

I just released the update, so if you're still using this (or interested in giving it another shot), please let me know if it's working for you now! If it's not, I'll re-open this ticket.

**Comment by sergei-dyshel** [comment]
@will-wow 
Unfortunately I'm no longer using your extension, but thank you anyway for addressing the issue :smile:
